def convertsmileys_python2 (text):
    newtext = str(text)
    
    newtext = newtext.replace(u'\ue415', '<img src="data/emoji/e415.png" alt=""/>')
    newtext = newtext.replace(u'\ue056', '<img src="data/emoji/e056.png" alt=""/>')
    newtext = newtext.replace(u'\ue057', '<img src="data/emoji/e057.png" alt=""/>')
    newtext = newtext.replace(u'\ue414', '<img src="data/emoji/e414.png" alt=""/>')
    newtext = newtext.replace(u'\ue405', '<img src="data/emoji/e405.png" alt=""/>')
    newtext = newtext.replace(u'\ue106', '<img src="data/emoji/e106.png" alt=""/>')
    newtext = newtext.replace(u'\ue418', '<img src="data/emoji/e418.png" alt=""/>')

    newtext = newtext.replace(u'\ue417', '<img src="data/emoji/e417.png" alt=""/>')
    newtext = newtext.replace(u'\ue40d', '<img src="data/emoji/e40d.png" alt=""/>')
    newtext = newtext.replace(u'\ue40a', '<img src="data/emoji/e40a.png" alt=""/>')
    newtext = newtext.replace(u'\ue404', '<img src="data/emoji/e404.png" alt=""/>')
    newtext = newtext.replace(u'\ue105', '<img src="data/emoji/e105.png" alt=""/>')
    newtext = newtext.replace(u'\ue409', '<img src="data/emoji/e409.png" alt=""/>')
    newtext = newtext.replace(u'\ue40e', '<img src="data/emoji/e40e.png" alt=""/>')

    newtext = newtext.replace(u'\ue402', '<img src="data/emoji/e402.png" alt=""/>')
    newtext = newtext.replace(u'\ue108', '<img src="data/emoji/e108.png" alt=""/>')
    newtext = newtext.replace(u'\ue403', '<img src="data/emoji/e403.png" alt=""/>')
    newtext = newtext.replace(u'\ue058', '<img src="data/emoji/e058.png" alt=""/>')
    newtext = newtext.replace(u'\ue407', '<img src="data/emoji/e407.png" alt=""/>')
    newtext = newtext.replace(u'\ue401', '<img src="data/emoji/e401.png" alt=""/>')
    newtext = newtext.replace(u'\ue40f', '<img src="data/emoji/e40f.png" alt=""/>')

    newtext = newtext.replace(u'\ue40b', '<img src="data/emoji/e40b.png" alt=""/>')
    newtext = newtext.replace(u'\ue406', '<img src="data/emoji/e406.png" alt=""/>')
    newtext = newtext.replace(u'\ue413', '<img src="data/emoji/e413.png" alt=""/>')
    newtext = newtext.replace(u'\ue411', '<img src="data/emoji/e411.png" alt=""/>')
    newtext = newtext.replace(u'\ue412', '<img src="data/emoji/e412.png" alt=""/>')
    newtext = newtext.replace(u'\ue410', '<img src="data/emoji/e410.png" alt=""/>')
    newtext = newtext.replace(u'\ue107', '<img src="data/emoji/e107.png" alt=""/>')

    newtext = newtext.replace(u'\ue059', '<img src="data/emoji/e059.png" alt=""/>')
    newtext = newtext.replace(u'\ue416', '<img src="data/emoji/e416.png" alt=""/>')
    newtext = newtext.replace(u'\ue408', '<img src="data/emoji/e408.png" alt=""/>')
    newtext = newtext.replace(u'\ue40c', '<img src="data/emoji/e40c.png" alt=""/>')
    newtext = newtext.replace(u'\ue11a', '<img src="data/emoji/e11a.png" alt=""/>')
    newtext = newtext.replace(u'\ue10c', '<img src="data/emoji/e10c.png" alt=""/>')
    newtext = newtext.replace(u'\ue32c', '<img src="data/emoji/e32c.png" alt=""/>')

    newtext = newtext.replace(u'\ue32a', '<img src="data/emoji/e32a.png" alt=""/>')
    newtext = newtext.replace(u'\ue32d', '<img src="data/emoji/e32d.png" alt=""/>')
    newtext = newtext.replace(u'\ue328', '<img src="data/emoji/e328.png" alt=""/>')
    newtext = newtext.replace(u'\ue32b', '<img src="data/emoji/e32b.png" alt=""/>')
    newtext = newtext.replace(u'\ue022', '<img src="data/emoji/e022.png" alt=""/>')
    newtext = newtext.replace(u'\ue023', '<img src="data/emoji/e023.png" alt=""/>')
    newtext = newtext.replace(u'\ue327', '<img src="data/emoji/e327.png" alt=""/>')

    newtext = newtext.replace(u'\ue329', '<img src="data/emoji/e329.png" alt=""/>')
    newtext = newtext.replace(u'\ue32e', '<img src="data/emoji/e32e.png" alt=""/>')
    newtext = newtext.replace(u'\ue32f', '<img src="data/emoji/e32f.png" alt=""/>')
    newtext = newtext.replace(u'\ue335', '<img src="data/emoji/e335.png" alt=""/>')
    newtext = newtext.replace(u'\ue334', '<img src="data/emoji/e334.png" alt=""/>')
    newtext = newtext.replace(u'\ue021', '<img src="data/emoji/e021.png" alt=""/>')
    newtext = newtext.replace(u'\ue337', '<img src="data/emoji/e337.png" alt=""/>')

    newtext = newtext.replace(u'\ue020', '<img src="data/emoji/e020.png" alt=""/>')
    newtext = newtext.replace(u'\ue336', '<img src="data/emoji/e336.png" alt=""/>')
    newtext = newtext.replace(u'\ue13c', '<img src="data/emoji/e13c.png" alt=""/>')
    newtext = newtext.replace(u'\ue330', '<img src="data/emoji/e330.png" alt=""/>')
    newtext = newtext.replace(u'\ue331', '<img src="data/emoji/e331.png" alt=""/>')
    newtext = newtext.replace(u'\ue326', '<img src="data/emoji/e326.png" alt=""/>')
    newtext = newtext.replace(u'\ue03e', '<img src="data/emoji/e03e.png" alt=""/>')

    newtext = newtext.replace(u'\ue11d', '<img src="data/emoji/e11d.png" alt=""/>')
    newtext = newtext.replace(u'\ue05a', '<img src="data/emoji/e05a.png" alt=""/>')
    newtext = newtext.replace(u'\ue00e', '<img src="data/emoji/e00e.png" alt=""/>')
    newtext = newtext.replace(u'\ue421', '<img src="data/emoji/e421.png" alt=""/>')
    newtext = newtext.replace(u'\ue420', '<img src="data/emoji/e420.png" alt=""/>')
    newtext = newtext.replace(u'\ue00d', '<img src="data/emoji/e00d.png" alt=""/>')
    newtext = newtext.replace(u'\ue010', '<img src="data/emoji/e010.png" alt=""/>')

    newtext = newtext.replace(u'\ue011', '<img src="data/emoji/e011.png" alt=""/>')
    newtext = newtext.replace(u'\ue41e', '<img src="data/emoji/e41e.png" alt=""/>')
    newtext = newtext.replace(u'\ue012', '<img src="data/emoji/e012.png" alt=""/>')
    newtext = newtext.replace(u'\ue422', '<img src="data/emoji/e422.png" alt=""/>')
    newtext = newtext.replace(u'\ue22e', '<img src="data/emoji/e22e.png" alt=""/>')
    newtext = newtext.replace(u'\ue22f', '<img src="data/emoji/e22f.png" alt=""/>')
    newtext = newtext.replace(u'\ue231', '<img src="data/emoji/e231.png" alt=""/>')

    newtext = newtext.replace(u'\ue230', '<img src="data/emoji/e230.png" alt=""/>')
    newtext = newtext.replace(u'\ue427', '<img src="data/emoji/e427.png" alt=""/>')
    newtext = newtext.replace(u'\ue41d', '<img src="data/emoji/e41d.png" alt=""/>')
    newtext = newtext.replace(u'\ue00f', '<img src="data/emoji/e00f.png" alt=""/>')
    newtext = newtext.replace(u'\ue41f', '<img src="data/emoji/e41f.png" alt=""/>')
    newtext = newtext.replace(u'\ue14c', '<img src="data/emoji/e14c.png" alt=""/>')
    newtext = newtext.replace(u'\ue201', '<img src="data/emoji/e201.png" alt=""/>')

    newtext = newtext.replace(u'\ue115', '<img src="data/emoji/e115.png" alt=""/>')
    newtext = newtext.replace(u'\ue428', '<img src="data/emoji/e428.png" alt=""/>')
    newtext = newtext.replace(u'\ue51f', '<img src="data/emoji/e51f.png" alt=""/>')
    newtext = newtext.replace(u'\ue429', '<img src="data/emoji/e429.png" alt=""/>')
    newtext = newtext.replace(u'\ue424', '<img src="data/emoji/e424.png" alt=""/>')
    newtext = newtext.replace(u'\ue423', '<img src="data/emoji/e423.png" alt=""/>')
    newtext = newtext.replace(u'\ue253', '<img src="data/emoji/e253.png" alt=""/>')

    newtext = newtext.replace(u'\ue426', '<img src="data/emoji/e426.png" alt=""/>')
    newtext = newtext.replace(u'\ue111', '<img src="data/emoji/e111.png" alt=""/>')
    newtext = newtext.replace(u'\ue425', '<img src="data/emoji/e425.png" alt=""/>')
    newtext = newtext.replace(u'\ue31e', '<img src="data/emoji/e31e.png" alt=""/>')
    newtext = newtext.replace(u'\ue31f', '<img src="data/emoji/e31f.png" alt=""/>')
    newtext = newtext.replace(u'\ue31d', '<img src="data/emoji/e31d.png" alt=""/>')
    newtext = newtext.replace(u'\ue001', '<img src="data/emoji/e001.png" alt=""/>')

    newtext = newtext.replace(u'\ue002', '<img src="data/emoji/e002.png" alt=""/>')
    newtext = newtext.replace(u'\ue005', '<img src="data/emoji/e005.png" alt=""/>')
    newtext = newtext.replace(u'\ue004', '<img src="data/emoji/e004.png" alt=""/>')
    newtext = newtext.replace(u'\ue51a', '<img src="data/emoji/e51a.png" alt=""/>')
    newtext = newtext.replace(u'\ue519', '<img src="data/emoji/e519.png" alt=""/>')
    newtext = newtext.replace(u'\ue518', '<img src="data/emoji/e518.png" alt=""/>')
    newtext = newtext.replace(u'\ue515', '<img src="data/emoji/e515.png" alt=""/>')

    newtext = newtext.replace(u'\ue516', '<img src="data/emoji/e516.png" alt=""/>')
    newtext = newtext.replace(u'\ue517', '<img src="data/emoji/e517.png" alt=""/>')
    newtext = newtext.replace(u'\ue51b', '<img src="data/emoji/e51b.png" alt=""/>')
    newtext = newtext.replace(u'\ue152', '<img src="data/emoji/e152.png" alt=""/>')
    newtext = newtext.replace(u'\ue04e', '<img src="data/emoji/e04e.png" alt=""/>')
    newtext = newtext.replace(u'\ue51c', '<img src="data/emoji/e51c.png" alt=""/>')
    newtext = newtext.replace(u'\ue51e', '<img src="data/emoji/e51e.png" alt=""/>')

    newtext = newtext.replace(u'\ue11c', '<img src="data/emoji/e11c.png" alt=""/>')
    newtext = newtext.replace(u'\ue536', '<img src="data/emoji/e536.png" alt=""/>')
    newtext = newtext.replace(u'\ue003', '<img src="data/emoji/e003.png" alt=""/>')
    newtext = newtext.replace(u'\ue41c', '<img src="data/emoji/e41c.png" alt=""/>')
    newtext = newtext.replace(u'\ue41b', '<img src="data/emoji/e41b.png" alt=""/>')
    newtext = newtext.replace(u'\ue419', '<img src="data/emoji/e419.png" alt=""/>')
    newtext = newtext.replace(u'\ue41a', '<img src="data/emoji/e41a.png" alt=""/>')

    newtext = newtext.replace(u'\ue04a', '<img src="data/emoji/e04a.png" alt=""/>')
    newtext = newtext.replace(u'\ue04b', '<img src="data/emoji/e04b.png" alt=""/>')
    newtext = newtext.replace(u'\ue049', '<img src="data/emoji/e049.png" alt=""/>')
    newtext = newtext.replace(u'\ue048', '<img src="data/emoji/e048.png" alt=""/>')
    newtext = newtext.replace(u'\ue04c', '<img src="data/emoji/e04c.png" alt=""/>')
    newtext = newtext.replace(u'\ue13d', '<img src="data/emoji/e13d.png" alt=""/>')
    newtext = newtext.replace(u'\ue443', '<img src="data/emoji/e443.png" alt=""/>')

    newtext = newtext.replace(u'\ue43e', '<img src="data/emoji/e43e.png" alt=""/>')
    newtext = newtext.replace(u'\ue04f', '<img src="data/emoji/e04f.png" alt=""/>')
    newtext = newtext.replace(u'\ue052', '<img src="data/emoji/e052.png" alt=""/>')
    newtext = newtext.replace(u'\ue053', '<img src="data/emoji/e053.png" alt=""/>')
    newtext = newtext.replace(u'\ue524', '<img src="data/emoji/e524.png" alt=""/>')
    newtext = newtext.replace(u'\ue52c', '<img src="data/emoji/e52c.png" alt=""/>')
    newtext = newtext.replace(u'\ue52a', '<img src="data/emoji/e52a.png" alt=""/>')

    newtext = newtext.replace(u'\ue531', '<img src="data/emoji/e531.png" alt=""/>')
    newtext = newtext.replace(u'\ue050', '<img src="data/emoji/e050.png" alt=""/>')
    newtext = newtext.replace(u'\ue527', '<img src="data/emoji/e527.png" alt=""/>')
    newtext = newtext.replace(u'\ue051', '<img src="data/emoji/e051.png" alt=""/>')
    newtext = newtext.replace(u'\ue10b', '<img src="data/emoji/e10b.png" alt=""/>')
    newtext = newtext.replace(u'\ue52b', '<img src="data/emoji/e52b.png" alt=""/>')
    newtext = newtext.replace(u'\ue52f', '<img src="data/emoji/e52f.png" alt=""/>')

    newtext = newtext.replace(u'\ue528', '<img src="data/emoji/e528.png" alt=""/>')
    newtext = newtext.replace(u'\ue01a', '<img src="data/emoji/e01a.png" alt=""/>')
    newtext = newtext.replace(u'\ue134', '<img src="data/emoji/e134.png" alt=""/>')
    newtext = newtext.replace(u'\ue530', '<img src="data/emoji/e530.png" alt=""/>')
    newtext = newtext.replace(u'\ue529', '<img src="data/emoji/e529.png" alt=""/>')
    newtext = newtext.replace(u'\ue526', '<img src="data/emoji/e526.png" alt=""/>')
    newtext = newtext.replace(u'\ue52d', '<img src="data/emoji/e52d.png" alt=""/>')

    newtext = newtext.replace(u'\ue521', '<img src="data/emoji/e521.png" alt=""/>')
    newtext = newtext.replace(u'\ue523', '<img src="data/emoji/e523.png" alt=""/>')
    newtext = newtext.replace(u'\ue52e', '<img src="data/emoji/e52e.png" alt=""/>')
    newtext = newtext.replace(u'\ue055', '<img src="data/emoji/e055.png" alt=""/>')
    newtext = newtext.replace(u'\ue525', '<img src="data/emoji/e525.png" alt=""/>')
    newtext = newtext.replace(u'\ue10a', '<img src="data/emoji/e10a.png" alt=""/>')
    newtext = newtext.replace(u'\ue109', '<img src="data/emoji/e109.png" alt=""/>')

    newtext = newtext.replace(u'\ue522', '<img src="data/emoji/e522.png" alt=""/>')
    newtext = newtext.replace(u'\ue019', '<img src="data/emoji/e019.png" alt=""/>')
    newtext = newtext.replace(u'\ue054', '<img src="data/emoji/e054.png" alt=""/>')
    newtext = newtext.replace(u'\ue520', '<img src="data/emoji/e520.png" alt=""/>')
    newtext = newtext.replace(u'\ue306', '<img src="data/emoji/e306.png" alt=""/>')
    newtext = newtext.replace(u'\ue030', '<img src="data/emoji/e030.png" alt=""/>')
    newtext = newtext.replace(u'\ue304', '<img src="data/emoji/e304.png" alt=""/>')

    newtext = newtext.replace(u'\ue110', '<img src="data/emoji/e110.png" alt=""/>')
    newtext = newtext.replace(u'\ue032', '<img src="data/emoji/e032.png" alt=""/>')
    newtext = newtext.replace(u'\ue305', '<img src="data/emoji/e305.png" alt=""/>')
    newtext = newtext.replace(u'\ue303', '<img src="data/emoji/e303.png" alt=""/>')
    newtext = newtext.replace(u'\ue118', '<img src="data/emoji/e118.png" alt=""/>')
    newtext = newtext.replace(u'\ue447', '<img src="data/emoji/e447.png" alt=""/>')
    newtext = newtext.replace(u'\ue119', '<img src="data/emoji/e119.png" alt=""/>')

    newtext = newtext.replace(u'\ue307', '<img src="data/emoji/e307.png" alt=""/>')
    newtext = newtext.replace(u'\ue308', '<img src="data/emoji/e308.png" alt=""/>')
    newtext = newtext.replace(u'\ue444', '<img src="data/emoji/e444.png" alt=""/>')
    newtext = newtext.replace(u'\ue441', '<img src="data/emoji/e441.png" alt=""/>')

    newtext = newtext.replace(u'\ue436', '<img src="data/emoji/e436.png" alt=""/>')
    newtext = newtext.replace(u'\ue437', '<img src="data/emoji/e437.png" alt=""/>')
    newtext = newtext.replace(u'\ue438', '<img src="data/emoji/e438.png" alt=""/>')
    newtext = newtext.replace(u'\ue43a', '<img src="data/emoji/e43a.png" alt=""/>')
    newtext = newtext.replace(u'\ue439', '<img src="data/emoji/e439.png" alt=""/>')
    newtext = newtext.replace(u'\ue43b', '<img src="data/emoji/e43b.png" alt=""/>')
    newtext = newtext.replace(u'\ue117', '<img src="data/emoji/e117.png" alt=""/>')

    newtext = newtext.replace(u'\ue440', '<img src="data/emoji/e440.png" alt=""/>')
    newtext = newtext.replace(u'\ue442', '<img src="data/emoji/e442.png" alt=""/>')
    newtext = newtext.replace(u'\ue446', '<img src="data/emoji/e446.png" alt=""/>')
    newtext = newtext.replace(u'\ue445', '<img src="data/emoji/e445.png" alt=""/>')
    newtext = newtext.replace(u'\ue11b', '<img src="data/emoji/e11b.png" alt=""/>')
    newtext = newtext.replace(u'\ue448', '<img src="data/emoji/e448.png" alt=""/>')
    newtext = newtext.replace(u'\ue033', '<img src="data/emoji/e033.png" alt=""/>')

    newtext = newtext.replace(u'\ue112', '<img src="data/emoji/e112.png" alt=""/>')
    newtext = newtext.replace(u'\ue325', '<img src="data/emoji/e325.png" alt=""/>')
    newtext = newtext.replace(u'\ue312', '<img src="data/emoji/e312.png" alt=""/>')
    newtext = newtext.replace(u'\ue310', '<img src="data/emoji/e310.png" alt=""/>')
    newtext = newtext.replace(u'\ue126', '<img src="data/emoji/e126.png" alt=""/>')
    newtext = newtext.replace(u'\ue127', '<img src="data/emoji/e127.png" alt=""/>')
    newtext = newtext.replace(u'\ue008', '<img src="data/emoji/e008.png" alt=""/>')

    newtext = newtext.replace(u'\ue03d', '<img src="data/emoji/e03d.png" alt=""/>')
    newtext = newtext.replace(u'\ue00c', '<img src="data/emoji/e00c.png" alt=""/>')
    newtext = newtext.replace(u'\ue12a', '<img src="data/emoji/e12a.png" alt=""/>')
    newtext = newtext.replace(u'\ue00a', '<img src="data/emoji/e00a.png" alt=""/>')
    newtext = newtext.replace(u'\ue00b', '<img src="data/emoji/e00b.png" alt=""/>')
    newtext = newtext.replace(u'\ue009', '<img src="data/emoji/e009.png" alt=""/>')
    newtext = newtext.replace(u'\ue316', '<img src="data/emoji/e316.png" alt=""/>')

    newtext = newtext.replace(u'\ue129', '<img src="data/emoji/e129.png" alt=""/>')
    newtext = newtext.replace(u'\ue141', '<img src="data/emoji/e141.png" alt=""/>')
    newtext = newtext.replace(u'\ue142', '<img src="data/emoji/e142.png" alt=""/>')
    newtext = newtext.replace(u'\ue317', '<img src="data/emoji/e317.png" alt=""/>')
    newtext = newtext.replace(u'\ue128', '<img src="data/emoji/e128.png" alt=""/>')
    newtext = newtext.replace(u'\ue14b', '<img src="data/emoji/e14b.png" alt=""/>')
    newtext = newtext.replace(u'\ue211', '<img src="data/emoji/e211.png" alt=""/>')

    newtext = newtext.replace(u'\ue114', '<img src="data/emoji/e114.png" alt=""/>')
    newtext = newtext.replace(u'\ue145', '<img src="data/emoji/e145.png" alt=""/>')
    newtext = newtext.replace(u'\ue144', '<img src="data/emoji/e144.png" alt=""/>')
    newtext = newtext.replace(u'\ue03f', '<img src="data/emoji/e03f.png" alt=""/>')
    newtext = newtext.replace(u'\ue313', '<img src="data/emoji/e313.png" alt=""/>')
    newtext = newtext.replace(u'\ue116', '<img src="data/emoji/e116.png" alt=""/>')
    newtext = newtext.replace(u'\ue10f', '<img src="data/emoji/e10f.png" alt=""/>')

    newtext = newtext.replace(u'\ue104', '<img src="data/emoji/e104.png" alt=""/>')
    newtext = newtext.replace(u'\ue103', '<img src="data/emoji/e103.png" alt=""/>')
    newtext = newtext.replace(u'\ue101', '<img src="data/emoji/e101.png" alt=""/>')
    newtext = newtext.replace(u'\ue102', '<img src="data/emoji/e102.png" alt=""/>')
    newtext = newtext.replace(u'\ue13f', '<img src="data/emoji/e13f.png" alt=""/>')
    newtext = newtext.replace(u'\ue140', '<img src="data/emoji/e140.png" alt=""/>')
    newtext = newtext.replace(u'\ue11f', '<img src="data/emoji/e11f.png" alt=""/>')

    newtext = newtext.replace(u'\ue12f', '<img src="data/emoji/e12f.png" alt=""/>')
    newtext = newtext.replace(u'\ue031', '<img src="data/emoji/e031.png" alt=""/>')
    newtext = newtext.replace(u'\ue30e', '<img src="data/emoji/e30e.png" alt=""/>')
    newtext = newtext.replace(u'\ue311', '<img src="data/emoji/e311.png" alt=""/>')
    newtext = newtext.replace(u'\ue113', '<img src="data/emoji/e113.png" alt=""/>')
    newtext = newtext.replace(u'\ue30f', '<img src="data/emoji/e30f.png" alt=""/>')
    newtext = newtext.replace(u'\ue13b', '<img src="data/emoji/e13b.png" alt=""/>')

    newtext = newtext.replace(u'\ue42b', '<img src="data/emoji/e42b.png" alt=""/>')
    newtext = newtext.replace(u'\ue42a', '<img src="data/emoji/e42a.png" alt=""/>')
    newtext = newtext.replace(u'\ue018', '<img src="data/emoji/e018.png" alt=""/>')
    newtext = newtext.replace(u'\ue016', '<img src="data/emoji/e016.png" alt=""/>')
    newtext = newtext.replace(u'\ue015', '<img src="data/emoji/e015.png" alt=""/>')
    newtext = newtext.replace(u'\ue014', '<img src="data/emoji/e014.png" alt=""/>')
    newtext = newtext.replace(u'\ue42c', '<img src="data/emoji/e42c.png" alt=""/>')

    newtext = newtext.replace(u'\ue42d', '<img src="data/emoji/e42d.png" alt=""/>')
    newtext = newtext.replace(u'\ue017', '<img src="data/emoji/e017.png" alt=""/>')
    newtext = newtext.replace(u'\ue013', '<img src="data/emoji/e013.png" alt=""/>')
    newtext = newtext.replace(u'\ue20e', '<img src="data/emoji/e20e.png" alt=""/>')
    newtext = newtext.replace(u'\ue20c', '<img src="data/emoji/e20c.png" alt=""/>')
    newtext = newtext.replace(u'\ue20f', '<img src="data/emoji/e20f.png" alt=""/>')
    newtext = newtext.replace(u'\ue20d', '<img src="data/emoji/e20d.png" alt=""/>')

    newtext = newtext.replace(u'\ue131', '<img src="data/emoji/e131.png" alt=""/>')
    newtext = newtext.replace(u'\ue12b', '<img src="data/emoji/e12b.png" alt=""/>')
    newtext = newtext.replace(u'\ue130', '<img src="data/emoji/e130.png" alt=""/>')
    newtext = newtext.replace(u'\ue12d', '<img src="data/emoji/e12d.png" alt=""/>')
    newtext = newtext.replace(u'\ue324', '<img src="data/emoji/e324.png" alt=""/>')
    newtext = newtext.replace(u'\ue301', '<img src="data/emoji/e301.png" alt=""/>')
    newtext = newtext.replace(u'\ue148', '<img src="data/emoji/e148.png" alt=""/>')

    newtext = newtext.replace(u'\ue502', '<img src="data/emoji/e502.png" alt=""/>')
    newtext = newtext.replace(u'\ue03c', '<img src="data/emoji/e03c.png" alt=""/>')
    newtext = newtext.replace(u'\ue30a', '<img src="data/emoji/e30a.png" alt=""/>')
    newtext = newtext.replace(u'\ue042', '<img src="data/emoji/e042.png" alt=""/>')
    newtext = newtext.replace(u'\ue040', '<img src="data/emoji/e040.png" alt=""/>')
    newtext = newtext.replace(u'\ue041', '<img src="data/emoji/e041.png" alt=""/>')
    newtext = newtext.replace(u'\ue12c', '<img src="data/emoji/e12c.png" alt=""/>')

    newtext = newtext.replace(u'\ue007', '<img src="data/emoji/e007.png" alt=""/>')
    newtext = newtext.replace(u'\ue31a', '<img src="data/emoji/e31a.png" alt=""/>')
    newtext = newtext.replace(u'\ue13e', '<img src="data/emoji/e13e.png" alt=""/>')
    newtext = newtext.replace(u'\ue31b', '<img src="data/emoji/e31b.png" alt=""/>')
    newtext = newtext.replace(u'\ue006', '<img src="data/emoji/e006.png" alt=""/>')
    newtext = newtext.replace(u'\ue302', '<img src="data/emoji/e302.png" alt=""/>')
    newtext = newtext.replace(u'\ue319', '<img src="data/emoji/e319.png" alt=""/>')

    newtext = newtext.replace(u'\ue321', '<img src="data/emoji/e321.png" alt=""/>')
    newtext = newtext.replace(u'\ue322', '<img src="data/emoji/e322.png" alt=""/>')
    newtext = newtext.replace(u'\ue314', '<img src="data/emoji/e314.png" alt=""/>')
    newtext = newtext.replace(u'\ue503', '<img src="data/emoji/e503.png" alt=""/>')
    newtext = newtext.replace(u'\ue10e', '<img src="data/emoji/e10e.png" alt=""/>')
    newtext = newtext.replace(u'\ue318', '<img src="data/emoji/e318.png" alt=""/>')
    newtext = newtext.replace(u'\ue43c', '<img src="data/emoji/e43c.png" alt=""/>')

    newtext = newtext.replace(u'\ue11e', '<img src="data/emoji/e11e.png" alt=""/>')
    newtext = newtext.replace(u'\ue323', '<img src="data/emoji/e323.png" alt=""/>')
    newtext = newtext.replace(u'\ue31c', '<img src="data/emoji/e31c.png" alt=""/>')
    newtext = newtext.replace(u'\ue034', '<img src="data/emoji/e034.png" alt=""/>')
    newtext = newtext.replace(u'\ue035', '<img src="data/emoji/e035.png" alt=""/>')
    newtext = newtext.replace(u'\ue045', '<img src="data/emoji/e045.png" alt=""/>')
    newtext = newtext.replace(u'\ue338', '<img src="data/emoji/e338.png" alt=""/>')

    newtext = newtext.replace(u'\ue047', '<img src="data/emoji/e047.png" alt=""/>')
    newtext = newtext.replace(u'\ue30c', '<img src="data/emoji/e30c.png" alt=""/>')
    newtext = newtext.replace(u'\ue044', '<img src="data/emoji/e044.png" alt=""/>')
    newtext = newtext.replace(u'\ue30b', '<img src="data/emoji/e30b.png" alt=""/>')
    newtext = newtext.replace(u'\ue043', '<img src="data/emoji/e043.png" alt=""/>')
    newtext = newtext.replace(u'\ue120', '<img src="data/emoji/e120.png" alt=""/>')
    newtext = newtext.replace(u'\ue33b', '<img src="data/emoji/e33b.png" alt=""/>')

    newtext = newtext.replace(u'\ue33f', '<img src="data/emoji/e33f.png" alt=""/>')
    newtext = newtext.replace(u'\ue341', '<img src="data/emoji/e341.png" alt=""/>')
    newtext = newtext.replace(u'\ue34c', '<img src="data/emoji/e34c.png" alt=""/>')
    newtext = newtext.replace(u'\ue344', '<img src="data/emoji/e344.png" alt=""/>')
    newtext = newtext.replace(u'\ue342', '<img src="data/emoji/e342.png" alt=""/>')
    newtext = newtext.replace(u'\ue33d', '<img src="data/emoji/e33d.png" alt=""/>')
    newtext = newtext.replace(u'\ue33e', '<img src="data/emoji/e33e.png" alt=""/>')

    newtext = newtext.replace(u'\ue340', '<img src="data/emoji/e340.png" alt=""/>')
    newtext = newtext.replace(u'\ue34d', '<img src="data/emoji/e34d.png" alt=""/>')
    newtext = newtext.replace(u'\ue339', '<img src="data/emoji/e339.png" alt=""/>')
    newtext = newtext.replace(u'\ue147', '<img src="data/emoji/e147.png" alt=""/>')
    newtext = newtext.replace(u'\ue343', '<img src="data/emoji/e343.png" alt=""/>')
    newtext = newtext.replace(u'\ue33c', '<img src="data/emoji/e33c.png" alt=""/>')
    newtext = newtext.replace(u'\ue33a', '<img src="data/emoji/e33a.png" alt=""/>')

    newtext = newtext.replace(u'\ue43f', '<img src="data/emoji/e43f.png" alt=""/>')
    newtext = newtext.replace(u'\ue34b', '<img src="data/emoji/e34b.png" alt=""/>')
    newtext = newtext.replace(u'\ue046', '<img src="data/emoji/e046.png" alt=""/>')
    newtext = newtext.replace(u'\ue345', '<img src="data/emoji/e345.png" alt=""/>')
    newtext = newtext.replace(u'\ue346', '<img src="data/emoji/e346.png" alt=""/>')
    newtext = newtext.replace(u'\ue348', '<img src="data/emoji/e348.png" alt=""/>')
    newtext = newtext.replace(u'\ue347', '<img src="data/emoji/e347.png" alt=""/>')

    newtext = newtext.replace(u'\ue34a', '<img src="data/emoji/e34a.png" alt=""/>')
    newtext = newtext.replace(u'\ue349', '<img src="data/emoji/e349.png" alt=""/>')

    newtext = newtext.replace(u'\ue036', '<img src="data/emoji/e036.png" alt=""/>')
    newtext = newtext.replace(u'\ue157', '<img src="data/emoji/e157.png" alt=""/>')
    newtext = newtext.replace(u'\ue038', '<img src="data/emoji/e038.png" alt=""/>')
    newtext = newtext.replace(u'\ue153', '<img src="data/emoji/e153.png" alt=""/>')
    newtext = newtext.replace(u'\ue155', '<img src="data/emoji/e155.png" alt=""/>')
    newtext = newtext.replace(u'\ue14d', '<img src="data/emoji/e14d.png" alt=""/>')
    newtext = newtext.replace(u'\ue156', '<img src="data/emoji/e156.png" alt=""/>')

    newtext = newtext.replace(u'\ue501', '<img src="data/emoji/e501.png" alt=""/>')
    newtext = newtext.replace(u'\ue158', '<img src="data/emoji/e158.png" alt=""/>')
    newtext = newtext.replace(u'\ue43d', '<img src="data/emoji/e43d.png" alt=""/>')
    newtext = newtext.replace(u'\ue037', '<img src="data/emoji/e037.png" alt=""/>')
    newtext = newtext.replace(u'\ue504', '<img src="data/emoji/e504.png" alt=""/>')
    newtext = newtext.replace(u'\ue44a', '<img src="data/emoji/e44a.png" alt=""/>')
    newtext = newtext.replace(u'\ue146', '<img src="data/emoji/e146.png" alt=""/>')

    newtext = newtext.replace(u'\ue50a', '<img src="data/emoji/e50a.png" alt=""/>')
    newtext = newtext.replace(u'\ue505', '<img src="data/emoji/e505.png" alt=""/>')
    newtext = newtext.replace(u'\ue506', '<img src="data/emoji/e506.png" alt=""/>')
    newtext = newtext.replace(u'\ue122', '<img src="data/emoji/e122.png" alt=""/>')
    newtext = newtext.replace(u'\ue508', '<img src="data/emoji/e508.png" alt=""/>')
    newtext = newtext.replace(u'\ue509', '<img src="data/emoji/e509.png" alt=""/>')
    newtext = newtext.replace(u'\ue03b', '<img src="data/emoji/e03b.png" alt=""/>')

    newtext = newtext.replace(u'\ue04d', '<img src="data/emoji/e04d.png" alt=""/>')
    newtext = newtext.replace(u'\ue449', '<img src="data/emoji/e449.png" alt=""/>')
    newtext = newtext.replace(u'\ue44b', '<img src="data/emoji/e44b.png" alt=""/>')
    newtext = newtext.replace(u'\ue51d', '<img src="data/emoji/e51d.png" alt=""/>')
    newtext = newtext.replace(u'\ue44c', '<img src="data/emoji/e44c.png" alt=""/>')
    newtext = newtext.replace(u'\ue124', '<img src="data/emoji/e124.png" alt=""/>')
    newtext = newtext.replace(u'\ue121', '<img src="data/emoji/e121.png" alt=""/>')

    newtext = newtext.replace(u'\ue433', '<img src="data/emoji/e433.png" alt=""/>')
    newtext = newtext.replace(u'\ue202', '<img src="data/emoji/e202.png" alt=""/>')
    newtext = newtext.replace(u'\ue135', '<img src="data/emoji/e135.png" alt=""/>')
    newtext = newtext.replace(u'\ue01c', '<img src="data/emoji/e01c.png" alt=""/>')
    newtext = newtext.replace(u'\ue01d', '<img src="data/emoji/e01d.png" alt=""/>')
    newtext = newtext.replace(u'\ue10d', '<img src="data/emoji/e10d.png" alt=""/>')
    newtext = newtext.replace(u'\ue136', '<img src="data/emoji/e136.png" alt=""/>')

    newtext = newtext.replace(u'\ue42e', '<img src="data/emoji/e42e.png" alt=""/>')
    newtext = newtext.replace(u'\ue01b', '<img src="data/emoji/e01b.png" alt=""/>')
    newtext = newtext.replace(u'\ue15a', '<img src="data/emoji/e15a.png" alt=""/>')
    newtext = newtext.replace(u'\ue159', '<img src="data/emoji/e159.png" alt=""/>')
    newtext = newtext.replace(u'\ue432', '<img src="data/emoji/e432.png" alt=""/>')
    newtext = newtext.replace(u'\ue430', '<img src="data/emoji/e430.png" alt=""/>')
    newtext = newtext.replace(u'\ue431', '<img src="data/emoji/e431.png" alt=""/>')

    newtext = newtext.replace(u'\ue42f', '<img src="data/emoji/e42f.png" alt=""/>')
    newtext = newtext.replace(u'\ue01e', '<img src="data/emoji/e01e.png" alt=""/>')
    newtext = newtext.replace(u'\ue039', '<img src="data/emoji/e039.png" alt=""/>')
    newtext = newtext.replace(u'\ue435', '<img src="data/emoji/e435.png" alt=""/>')
    newtext = newtext.replace(u'\ue01f', '<img src="data/emoji/e01f.png" alt=""/>')
    newtext = newtext.replace(u'\ue125', '<img src="data/emoji/e125.png" alt=""/>')
    newtext = newtext.replace(u'\ue03a', '<img src="data/emoji/e03a.png" alt=""/>')

    newtext = newtext.replace(u'\ue14e', '<img src="data/emoji/e14e.png" alt=""/>')
    newtext = newtext.replace(u'\ue252', '<img src="data/emoji/e252.png" alt=""/>')
    newtext = newtext.replace(u'\ue137', '<img src="data/emoji/e137.png" alt=""/>')
    newtext = newtext.replace(u'\ue209', '<img src="data/emoji/e209.png" alt=""/>')
    newtext = newtext.replace(u'\ue154', '<img src="data/emoji/e154.png" alt=""/>')
    newtext = newtext.replace(u'\ue133', '<img src="data/emoji/e133.png" alt=""/>')
    newtext = newtext.replace(u'\ue150', '<img src="data/emoji/e150.png" alt=""/>')

    newtext = newtext.replace(u'\ue320', '<img src="data/emoji/e320.png" alt=""/>')
    newtext = newtext.replace(u'\ue123', '<img src="data/emoji/e123.png" alt=""/>')
    newtext = newtext.replace(u'\ue132', '<img src="data/emoji/e132.png" alt=""/>')
    newtext = newtext.replace(u'\ue143', '<img src="data/emoji/e143.png" alt=""/>')
    newtext = newtext.replace(u'\ue50b', '<img src="data/emoji/e50b.png" alt=""/>')
    newtext = newtext.replace(u'\ue514', '<img src="data/emoji/e514.png" alt=""/>')
    newtext = newtext.replace(u'\ue513', '<img src="data/emoji/e513.png" alt=""/>')

    newtext = newtext.replace(u'\ue50c', '<img src="data/emoji/e50c.png" alt=""/>')
    newtext = newtext.replace(u'\ue50d', '<img src="data/emoji/e50d.png" alt=""/>')
    newtext = newtext.replace(u'\ue511', '<img src="data/emoji/e511.png" alt=""/>')
    newtext = newtext.replace(u'\ue50f', '<img src="data/emoji/e50f.png" alt=""/>')
    newtext = newtext.replace(u'\ue512', '<img src="data/emoji/e512.png" alt=""/>')
    newtext = newtext.replace(u'\ue510', '<img src="data/emoji/e510.png" alt=""/>')
    newtext = newtext.replace(u'\ue50e', '<img src="data/emoji/e50e.png" alt=""/>')

    newtext = newtext.replace(u'\ue21c', '<img src="data/emoji/e21c.png" alt=""/>')
    newtext = newtext.replace(u'\ue21d', '<img src="data/emoji/e21d.png" alt=""/>')
    newtext = newtext.replace(u'\ue21e', '<img src="data/emoji/e21e.png" alt=""/>')
    newtext = newtext.replace(u'\ue21f', '<img src="data/emoji/e21f.png" alt=""/>')
    newtext = newtext.replace(u'\ue220', '<img src="data/emoji/e220.png" alt=""/>')
    newtext = newtext.replace(u'\ue221', '<img src="data/emoji/e221.png" alt=""/>')
    newtext = newtext.replace(u'\ue222', '<img src="data/emoji/e222.png" alt=""/>')

    newtext = newtext.replace(u'\ue223', '<img src="data/emoji/e223.png" alt=""/>')
    newtext = newtext.replace(u'\ue224', '<img src="data/emoji/e224.png" alt=""/>')
    newtext = newtext.replace(u'\ue225', '<img src="data/emoji/e225.png" alt=""/>')
    newtext = newtext.replace(u'\ue210', '<img src="data/emoji/e210.png" alt=""/>')
    newtext = newtext.replace(u'\ue232', '<img src="data/emoji/e232.png" alt=""/>')
    newtext = newtext.replace(u'\ue233', '<img src="data/emoji/e233.png" alt=""/>')
    newtext = newtext.replace(u'\ue235', '<img src="data/emoji/e235.png" alt=""/>')

    newtext = newtext.replace(u'\ue234', '<img src="data/emoji/e234.png" alt=""/>')
    newtext = newtext.replace(u'\ue236', '<img src="data/emoji/e236.png" alt=""/>')
    newtext = newtext.replace(u'\ue237', '<img src="data/emoji/e237.png" alt=""/>')
    newtext = newtext.replace(u'\ue238', '<img src="data/emoji/e238.png" alt=""/>')
    newtext = newtext.replace(u'\ue239', '<img src="data/emoji/e239.png" alt=""/>')
    newtext = newtext.replace(u'\ue23b', '<img src="data/emoji/e23b.png" alt=""/>')
    newtext = newtext.replace(u'\ue23a', '<img src="data/emoji/e23a.png" alt=""/>')

    newtext = newtext.replace(u'\ue23d', '<img src="data/emoji/e23d.png" alt=""/>')
    newtext = newtext.replace(u'\ue23c', '<img src="data/emoji/e23c.png" alt=""/>')
    newtext = newtext.replace(u'\ue24d', '<img src="data/emoji/e24d.png" alt=""/>')
    newtext = newtext.replace(u'\ue212', '<img src="data/emoji/e212.png" alt=""/>')
    newtext = newtext.replace(u'\ue24c', '<img src="data/emoji/e24c.png" alt=""/>')
    newtext = newtext.replace(u'\ue213', '<img src="data/emoji/e213.png" alt=""/>')
    newtext = newtext.replace(u'\ue214', '<img src="data/emoji/e214.png" alt=""/>')

    newtext = newtext.replace(u'\ue507', '<img src="data/emoji/e507.png" alt=""/>')
    newtext = newtext.replace(u'\ue203', '<img src="data/emoji/e203.png" alt=""/>')
    newtext = newtext.replace(u'\ue20b', '<img src="data/emoji/e20b.png" alt=""/>')
    newtext = newtext.replace(u'\ue22a', '<img src="data/emoji/e22a.png" alt=""/>')
    newtext = newtext.replace(u'\ue22b', '<img src="data/emoji/e22b.png" alt=""/>')
    newtext = newtext.replace(u'\ue226', '<img src="data/emoji/e226.png" alt=""/>')
    newtext = newtext.replace(u'\ue227', '<img src="data/emoji/e227.png" alt=""/>')

    newtext = newtext.replace(u'\ue22c', '<img src="data/emoji/e22c.png" alt=""/>')
    newtext = newtext.replace(u'\ue22d', '<img src="data/emoji/e22d.png" alt=""/>')
    newtext = newtext.replace(u'\ue215', '<img src="data/emoji/e215.png" alt=""/>')
    newtext = newtext.replace(u'\ue216', '<img src="data/emoji/e216.png" alt=""/>')
    newtext = newtext.replace(u'\ue217', '<img src="data/emoji/e217.png" alt=""/>')
    newtext = newtext.replace(u'\ue218', '<img src="data/emoji/e218.png" alt=""/>')
    newtext = newtext.replace(u'\ue228', '<img src="data/emoji/e228.png" alt=""/>')

    newtext = newtext.replace(u'\ue151', '<img src="data/emoji/e151.png" alt=""/>')
    newtext = newtext.replace(u'\ue138', '<img src="data/emoji/e138.png" alt=""/>')
    newtext = newtext.replace(u'\ue139', '<img src="data/emoji/e139.png" alt=""/>')
    newtext = newtext.replace(u'\ue13a', '<img src="data/emoji/e13a.png" alt=""/>')
    newtext = newtext.replace(u'\ue208', '<img src="data/emoji/e208.png" alt=""/>')
    newtext = newtext.replace(u'\ue14f', '<img src="data/emoji/e14f.png" alt=""/>')
    newtext = newtext.replace(u'\ue20a', '<img src="data/emoji/e20a.png" alt=""/>')

    newtext = newtext.replace(u'\ue434', '<img src="data/emoji/e434.png" alt=""/>')
    newtext = newtext.replace(u'\ue309', '<img src="data/emoji/e309.png" alt=""/>')
    newtext = newtext.replace(u'\ue315', '<img src="data/emoji/e315.png" alt=""/>')
    newtext = newtext.replace(u'\ue30d', '<img src="data/emoji/e30d.png" alt=""/>')
    newtext = newtext.replace(u'\ue207', '<img src="data/emoji/e207.png" alt=""/>')
    newtext = newtext.replace(u'\ue229', '<img src="data/emoji/e229.png" alt=""/>')
    newtext = newtext.replace(u'\ue206', '<img src="data/emoji/e206.png" alt=""/>')

    newtext = newtext.replace(u'\ue205', '<img src="data/emoji/e205.png" alt=""/>')
    newtext = newtext.replace(u'\ue204', '<img src="data/emoji/e204.png" alt=""/>')
    newtext = newtext.replace(u'\ue12e', '<img src="data/emoji/e12e.png" alt=""/>')
    newtext = newtext.replace(u'\ue250', '<img src="data/emoji/e250.png" alt=""/>')
    newtext = newtext.replace(u'\ue251', '<img src="data/emoji/e251.png" alt=""/>')
    newtext = newtext.replace(u'\ue14a', '<img src="data/emoji/e14a.png" alt=""/>')
    newtext = newtext.replace(u'\ue149', '<img src="data/emoji/e149.png" alt=""/>')

    newtext = newtext.replace(u'\ue23f', '<img src="data/emoji/e23f.png" alt=""/>')
    newtext = newtext.replace(u'\ue240', '<img src="data/emoji/e240.png" alt=""/>')
    newtext = newtext.replace(u'\ue241', '<img src="data/emoji/e241.png" alt=""/>')
    newtext = newtext.replace(u'\ue242', '<img src="data/emoji/e242.png" alt=""/>')
    newtext = newtext.replace(u'\ue243', '<img src="data/emoji/e243.png" alt=""/>')
    newtext = newtext.replace(u'\ue244', '<img src="data/emoji/e244.png" alt=""/>')
    newtext = newtext.replace(u'\ue245', '<img src="data/emoji/e245.png" alt=""/>')

    newtext = newtext.replace(u'\ue246', '<img src="data/emoji/e246.png" alt=""/>')
    newtext = newtext.replace(u'\ue247', '<img src="data/emoji/e247.png" alt=""/>')
    newtext = newtext.replace(u'\ue248', '<img src="data/emoji/e248.png" alt=""/>')
    newtext = newtext.replace(u'\ue249', '<img src="data/emoji/e249.png" alt=""/>')
    newtext = newtext.replace(u'\ue24a', '<img src="data/emoji/e24a.png" alt=""/>')
    newtext = newtext.replace(u'\ue24b', '<img src="data/emoji/e24b.png" alt=""/>')
    newtext = newtext.replace(u'\ue23e', '<img src="data/emoji/e23e.png" alt=""/>')

    newtext = newtext.replace(u'\ue532', '<img src="data/emoji/e532.png" alt=""/>')
    newtext = newtext.replace(u'\ue533', '<img src="data/emoji/e533.png" alt=""/>')
    newtext = newtext.replace(u'\ue534', '<img src="data/emoji/e534.png" alt=""/>')
    newtext = newtext.replace(u'\ue535', '<img src="data/emoji/e535.png" alt=""/>')
    newtext = newtext.replace(u'\ue21a', '<img src="data/emoji/e21a.png" alt=""/>')
    newtext = newtext.replace(u'\ue219', '<img src="data/emoji/e219.png" alt=""/>')
    newtext = newtext.replace(u'\ue21b', '<img src="data/emoji/e21b.png" alt=""/>')

    newtext = newtext.replace(u'\ue02f', '<img src="data/emoji/e02f.png" alt=""/>')
    newtext = newtext.replace(u'\ue024', '<img src="data/emoji/e024.png" alt=""/>')
    newtext = newtext.replace(u'\ue025', '<img src="data/emoji/e025.png" alt=""/>')
    newtext = newtext.replace(u'\ue026', '<img src="data/emoji/e026.png" alt=""/>')
    newtext = newtext.replace(u'\ue027', '<img src="data/emoji/e027.png" alt=""/>')
    newtext = newtext.replace(u'\ue028', '<img src="data/emoji/e028.png" alt=""/>')
    newtext = newtext.replace(u'\ue029', '<img src="data/emoji/e029.png" alt=""/>')

    newtext = newtext.replace(u'\ue02a', '<img src="data/emoji/e02a.png" alt=""/>')
    newtext = newtext.replace(u'\ue02b', '<img src="data/emoji/e02b.png" alt=""/>')
    newtext = newtext.replace(u'\ue02c', '<img src="data/emoji/e02c.png" alt=""/>')
    newtext = newtext.replace(u'\ue02d', '<img src="data/emoji/e02d.png" alt=""/>')
    newtext = newtext.replace(u'\ue02e', '<img src="data/emoji/e02e.png" alt=""/>')
    newtext = newtext.replace(u'\ue332', '<img src="data/emoji/e332.png" alt=""/>')
    newtext = newtext.replace(u'\ue333', '<img src="data/emoji/e333.png" alt=""/>')

    newtext = newtext.replace(u'\ue24e', '<img src="data/emoji/e24e.png" alt=""/>')
    newtext = newtext.replace(u'\ue24f', '<img src="data/emoji/e24f.png" alt=""/>')
    newtext = newtext.replace(u'\ue537', '<img src="data/emoji/e537.png" alt=""/>')   

    return newtext